import Link from "next/link";
import { getData } from "@/lib/content";
import { getDevelopment, TARGET_DEVELOPMENT_FILMS, TARGET_GROUPS } from "@/lib/development";

export default async function ArcPage() {
  const [data, dev] = await Promise.all([getData(), getDevelopment()]);
  const assigned = dev.conceptGroup.size;
  const unassigned = [...data.concepts.keys()].filter((id) => !dev.conceptGroup.has(id));
  const filmsOk = dev.draftFilmTotal === TARGET_DEVELOPMENT_FILMS;
  const lastGroup = dev.groups.at(-1);

  return (
    <>
      <header className="page-header">
        <div className="eyebrow">03 / Chronological order</div>
        <h1>Story arc</h1>
        <p>
          The ten chronological groups, in story order. Each group explores one connected cluster of concepts, follows one emotional
          stage of the journey, and introduces one object in its first film. Everything here is a <strong>draft</strong> awaiting review.
        </p>
      </header>

      <section className="summary" aria-label="Arc summary">
        <div><strong>{dev.groups.length}/{TARGET_GROUPS}</strong><span>chronological groups</span></div>
        <div><strong className={filmsOk ? "" : "warn"}>{dev.draftFilmTotal}/{TARGET_DEVELOPMENT_FILMS}</strong><span>draft films (Ep 2–99)</span></div>
        <div><strong className={unassigned.length ? "warn" : ""}>{assigned}/{data.concepts.size}</strong><span>concepts placed</span></div>
        <div><strong>{dev.objects.size}</strong><span>objects (unnamed)</span></div>
      </section>

      <section className="arc-timeline" aria-label="Chronological timeline">
        <div className="arc-bar">
          {dev.groups.map((group) => (
            <Link
              key={group.id}
              href={`/arc/${group.id}`}
              className="arc-segment"
              style={{ flexGrow: group.draft_film_count }}
              title={`${group.title}: ${group.draft_film_count} films`}
            >
              <span>{String(group.chronological_position).padStart(2, "0")}</span>
              <b>{group.emotional_stage}</b>
              <small>{group.draft_film_count}</small>
            </Link>
          ))}
          <div className="arc-framing" title="Framing films: not generated by the screenplay system">
            <span>Frame</span>
            <b>Crowd → 100A → 1 → 100B</b>
          </div>
        </div>
        <p className="arc-caption">
          Width = draft film count. After Group 10 the chronology reaches the crowd, then Episode 100 Part A, Episode 1, and
          Episode 100 Part B.
        </p>
      </section>

      {unassigned.length > 0 && (
        <p className="notice warn">Concepts not yet placed in a group: {unassigned.join(", ")}</p>
      )}

      <div className="group-grid">
        {dev.groups.map((group) => {
          const object = dev.objects.get(group.object_id);
          return (
            <Link className="group-card" href={`/arc/${group.id}`} key={group.id}>
              <div className="group-card-head">
                <span className="group-number">{String(group.chronological_position).padStart(2, "0")}</span>
                <span className="badge">{group.status}</span>
              </div>
              <div className="group-stage">{group.emotional_stage}</div>
              <h2>{group.title}</h2>
              <p>{group.human_question}</p>
              <div className="group-meta">
                <span>{group.draft_film_count} films</span>
                <span>{group.concepts.length} concepts</span>
                <span>{object?.title ?? group.object_id}</span>
              </div>
            </Link>
          );
        })}
      </div>

      <section className="concept-section">
        <div className="section-heading"><span>FR</span><h2>Framing films</h2><small>continuity references only</small></div>
        <p className="muted-note">
          Episodes 1 and 100 show the same event told two ways. They are stored separately and are never generated by the
          screenplay system, which covers Episodes 2–99 only.
        </p>
        <div className="concept-list">
          {dev.framing.map((episode) => (
            <div className="framing-row" key={episode.id}>
              <strong>Ep {episode.release.public_number}</strong>
              <div>
                <b>{episode.title}</b>
                <ol>{episode.sequence.map((step) => <li key={step}>{step}</li>)}</ol>
              </div>
              <a href={episode.external_screenplay} target="_blank" rel="noreferrer">Screenplay ↗</a>
            </div>
          ))}
        </div>
        {lastGroup && (
          <p className="muted-note">
            Release rule: the last chronological film of {lastGroup.id} ({lastGroup.title}) is released as Episode 99 and ends on the crowd,
            so it hands straight into Episode 100.
          </p>
        )}
      </section>
    </>
  );
}
