# -*- coding: utf-8 -*-
"""Build data/stories.json: selection, story IDs, release order, seasons, chronology."""
import json, os
H=os.path.dirname(os.path.dirname(os.path.abspath(__file__))); D=os.path.join(H,"data")
leads={l["lead_id"]:l for l in json.load(open(os.path.join(D,"leads.json")))}

REJECTED={
 "SL-SQ24-001":"Research direction only. No troupe, village or scheduled performance located, and the form's caste-satire content needs a worked-out position with performers before anything could be filmed.",
 "SL-SQ21-005":"Research direction only. A monument with no identified subject and nothing currently happening.",
 "SL-SQ24-003":"Research direction only. Every source found was a commercial astrology service. No independent evidence of how families actually decide.",
 "SL-SQ05-002":"Single commercial property source. The premise that resident families are being displaced by value is plausible and entirely unevidenced.",
 "SL-SQ08-006":"No working blacksmith located. Encyclopaedic background is not a subject.",
 "SL-SQ02-003":"No living carving practice at or near Embekke established. Without it this is a monument, not a documentary.",
 "SL-SQ03-008":"No human subject with anything at stake. Available material is either promotional or oppositional.",
 "SL-SQ22-009":"No family, association or event identified, and the community's own boundaries are contested within the sources.",
 "SL-SQ22-002":"No seed-keeping farmer identified. Health claims in the trade sources are unusable.",
 "SL-SQ08-001":"Strong subject area, no located subject. A completed technological transition with nobody found who made it.",
 "SL-SQ16-003":"Camps documented only in a personal account and tourism copy. The financing arrangement may involve debt bondage and that was neither confirmed nor excluded; it must not be scheduled on this evidence.",
}

SEASONS=[
 dict(id="S01", title="What you notice", episodes=8, question="What decides what we actually see and hear?",
  assumption="That perceiving is passive and complete: that what is in front of a person simply arrives.",
  contrasts="A drum maker listening for a tone against a coir worker whose product nobody looks at; a puppeteer's hand that the audience never watches against a bird counter who must take a flock one at a time.",
  shift="Attention is an act with a cost, and it selects. By the end of the season the audience has watched several people whose whole skill is a way of attending, and one place where the attending is itself doing damage.",
  prepares="If seeing is selective, the next question is what the selection turns things into.",
  ep1_effect="Episode 1 was watched before any of this. On a second viewing the monastery sequence reads as somebody learning to attend, not somebody arriving somewhere.",
  piece="SP-01",
  eps=["SL-SQ02-001","SL-SQ01-002","SL-SQ01-001","SL-SQ02-002","SL-SQ01-003","SL-SQ01-004","SL-SQ01-006"]),
 dict(id="S02", title="What you take a thing to be", episodes=9, question="When does recognising something become deciding what it is?",
  assumption="That a confident recognition is the same as understanding.",
  contrasts="A tune that sells bread without anyone looking at the bread, against a disease recognised by its signs for thirty years with no agreed cause; a guide who sees what a visitor cannot, against a law that turned a way of living into an offence.",
  shift="Recognition can be fast, firm, useful and still carry no understanding, and the names it produces can outlast the thing they described.",
  prepares="If a name can stick to a person, so can a want. The next season turns to what people reach for.",
  ep1_effect="The monastery in Episode 1 is a place the audience recognised instantly. This season makes that instant recognition suspect.",
  piece="SP-02",
  eps=["SL-SQ03-007","SL-SQ01-005","SL-SQ03-001","SL-SQ02-004","SL-SQ03-006","SL-SQ03-002","SL-SQ03-003","SL-SQ03-004","SL-SQ03-005"]),
 dict(id="S03", title="Wanting, having and enough", episodes=10, question="What keeps something wanted after the cost of it is clear?",
  assumption="That wanting is simple, and that people who keep wanting something have not understood what it costs.",
  contrasts="Pilgrims who walk for two months carrying almost nothing, against a safari driver whose income depends on producing a leopard; a tea taster whose palate is a calibration, against a freelancer whose income separates them from their street.",
  shift="Wanting is not one thing. It can be a reason to go without, a trap built by an incentive, or a measurement against whatever you happen to be used to.",
  prepares="Wanting something does not produce the effort to get it. The next season is about what does.",
  ep1_effect="Whatever Chathura went to the monastery for, this season makes it harder to call it renunciation.",
  piece="SP-03",
  eps=["SL-SQ05-001","SL-SQ06-001","SL-SQ06-002","SL-SQ06-003","SL-SQ06-004","SL-SQ02-006","SL-SQ13-001","SL-SQ04-001","SL-SQ04-002","SL-SQ13-002"]),
 dict(id="S04", title="Effort, readiness and the conditions for acting", episodes=10, question="What has to be true before a person can act at all?",
  assumption="That effort is a matter of will, and that people who do not act have not decided to.",
  contrasts="A tapper climbing before the heat against a salt worker who cannot hurry the sun; an ambulance crew whose skill is measured in seconds against a household that has been told its house is unsafe and has not moved.",
  shift="Readiness is made of conditions: a body, a season, a price, a road, a rule. Deciding is not moving.",
  prepares="If acting depends on conditions, so does learning. The next season asks how anyone can tell they are getting better.",
  ep1_effect="Arriving at a monastery is an act with conditions behind it, and Episode 100 will show what they were.",
  piece="SP-04",
  eps=["SL-SQ07-001","SL-SQ07-004","SL-SQ08-002","SL-SQ09-002","SL-SQ07-002","SL-SQ07-003","SL-SQ08-004","SL-SQ08-007","SL-SQ10-004","SL-SQ08-005"]),
 dict(id="S05", title="Learning, mastery and the judgement of progress", episodes=11, question="How do we know whether we are getting anywhere?",
  assumption="That progress can be measured, and that someone qualified can tell you where you are.",
  contrasts="A dancer whose teacher decides when he may wear the costume, against a lighthouse keeper with nobody to judge him; a ten-year-old sitting a national examination, against a weaving village counting how many households are left.",
  shift="Some learning cannot be described, some cannot be examined, and some of what looks like arrival is a place you passed through.",
  prepares="Having a skill raises the question of what it is for, and who it is given to.",
  ep1_effect="Nothing in Episode 1 tells the audience whether Chathura is a beginner. This season makes that a real question rather than an assumption.",
  piece="SP-05",
  eps=["SL-SQ10-002","SL-SQ10-003","SL-SQ10-007","SL-SQ09-003","SL-SQ10-005","SL-SQ10-008","SL-SQ10-006","SL-SQ09-001","SL-SQ02-005","SL-SQ21-006","SL-SQ10-001"]),
 dict(id="S06", title="Giving and what moves it", episodes=10, question="What is actually happening when somebody gives something away?",
  assumption="That generosity is self-explanatory, and that the act tells you the reason.",
  contrasts="A dansal that gives away everything it makes, against a stall on a mountain trail that is both devotion and a business; a blood donor who gives what they need, against men paid to guard the eggs they used to sell.",
  shift="The same act carries different reasons, and some restraint is indistinguishable from generosity until you ask who is watching.",
  prepares="Restraint when nobody is watching leads directly to fairness when everybody is.",
  ep1_effect="A monastery runs on other people's giving. Episode 1 never shows who fed anyone.",
  piece="SP-06",
  eps=["SL-SQ12-003","SL-SQ11-001","SL-SQ12-002","SL-SQ11-002","SL-SQ11-003","SL-SQ12-001","SL-SQ14-001","SL-SQ15-002","SL-SQ15-004","SL-SQ14-002"]),
 dict(id="S07", title="Conscience, fairness and what is shared", episodes=10, question="How does something held in common become something that can be taken?",
  assumption="That unfairness is caused by bad people, and that naming the cause is straightforward.",
  contrasts="A river mined at night in breach of a court order, against a village that hands one person the power to open a sluice; a policy decided quickly and paid for over years, against a market where a night's price is taken over from whatever everyone else is doing.",
  shift="Division is a process, not a villain. Fear, custom, incentive and a single confident decision all do the work that gets blamed on greed.",
  prepares="If fairness is this hard between strangers, the next season asks what it looks like between people who are responsible for each other.",
  ep1_effect="Chathura arrives somewhere that is outside all of this, which is a position that has to be paid for by someone.",
  piece="SP-07",
  eps=["SL-SQ15-003","SL-SQ23-004","SL-SQ15-001","SL-SQ23-001","SL-SQ24-004","SL-SQ23-007","SL-SQ23-002","SL-SQ23-008","SL-SQ23-003","SL-SQ24-005"]),
 dict(id="S08", title="Care and the limits of helping", episodes=11, question="When is stepping back a way of caring, and when is it not?",
  assumption="That care means closeness, and that more of it is always better.",
  contrasts="Keepers who deliberately minimise contact with the animals they are raising, against a woman who leaves the country so that her family can stay in it; a dog that a street half-owns, against a person who has to travel a hundred kilometres to renew a prescription.",
  shift="Care has a shape and a limit. Some of it works by withdrawing, some of it never arrives, and some of it is being done by people nobody is looking at.",
  prepares="Every one of these relationships ends. The next season is about what that does.",
  ep1_effect="Episode 1 shows a person who has stepped away from everyone. This season makes that neither noble nor cold by default.",
  piece="SP-08",
  eps=["SL-SQ17-003","SL-SQ16-001","SL-SQ24-002","SL-SQ17-001","SL-SQ17-002","SL-SQ23-009","SL-SQ22-004","SL-SQ23-006","SL-SQ16-002","SL-SQ19-003","SL-SQ17-004"]),
 dict(id="S09", title="Loss, ending and what can still be done", episodes=10, question="What is left to do for something that has already ended?",
  assumption="That grief is a phase that closes, and that an answer or a payment can close it.",
  contrasts="A family holding an almsgiving for someone who cannot receive it, against families who refuse a sum of money because they were asking a different question; mangroves replanted where a farm destroyed them, against a village now under a reservoir.",
  shift="Repair changes the weight of the past without erasing it, and some of what people do after a loss is not repair at all but a way of continuing to attend.",
  prepares="If what is gone does not simply close, the last season can ask what continuity actually is.",
  ep1_effect="Episode 1 ends with a disappearance. This season teaches the audience not to read a disappearance as an ending.",
  piece="SP-09",
  eps=["SL-SQ18-003","SL-SQ18-004","SL-SQ19-002","SL-SQ18-002","SL-SQ22-008","SL-SQ22-001","SL-SQ19-001","SL-SQ18-005","SL-SQ20-001","SL-SQ18-001"]),
 dict(id="S10", title="Change, memory and returning", episodes=10, question="What makes something still the same thing after everything in it has been replaced?",
  assumption="That a place, a craft or a person is a fixed thing that either survives or does not.",
  contrasts="A casting method in which the original must be destroyed to make the object, against a workshop in its fifth generation; a coastline that is wearing away, against a railway that stays the same by being continuously replaced.",
  shift="Continuity is made of replacement. What returns to a place does not find the place, and the series ends at the end of a line that was destroyed and rebuilt on its own formation.",
  prepares="Nothing. This is where the public journey stops and Episode 100 begins.",
  ep1_effect="Everything. By this point the audience has been taught that a return is not a recovery, which is exactly the reading Episode 100 needs them to bring to Episode 1.",
  piece="SP-10",
  eps=["SL-SQ21-002","SL-SQ21-001","SL-SQ21-008","SL-SQ21-003","SL-SQ22-007","SL-SQ21-007","SL-SQ22-003","SL-SQ22-010","SL-SQ21-004","SL-SQ22-005"]),
]

# ---- chronology phases (partial order; membership is provisional) ----
PHASES=[("P1","Before the journey is a journey","West coast and Colombo: the places reachable without committing to anything."),
        ("P2","Outward","The southern and south-western coast."),
        ("P3","Upward","The hill country, Sabaragamuwa and the central districts."),
        ("P4","Across","Uva and the Eastern province."),
        ("P5","North","The Northern province."),
        ("P6","Back through the middle","North Western and North Central."),
        ("P7","Not assigned","Island-wide, multi-district or place-not-established stories. No phase is claimed for these.")]

PHASE={  # lead_id -> (phase, confidence, calendar constraint or "")
 "SL-SQ02-001":("P3","seasonal",""), "SL-SQ01-002":("P1","unconstrained",""),
 "SL-SQ01-001":("P2","fixed-date","Performances traditionally at temples in May and June."),
 "SL-SQ02-002":("P3","unconstrained",""), "SL-SQ01-003":("P1","unconstrained",""),
 "SL-SQ01-004":("P2","fixed-date","Migratory season September to March; ringing in December and February."),
 "SL-SQ01-006":("P6","seasonal",""), "SL-SQ03-007":("P7","unconstrained",""),
 "SL-SQ01-005":("P3","seasonal","Sinharaja is wettest in the inter-monsoon months."),
 "SL-SQ03-001":("P3","unconstrained",""), "SL-SQ02-004":("P6","seasonal","Aranyas commonly close to visitors during the rains retreat."),
 "SL-SQ03-006":("P7","seasonal","Bites peak with the paddy calendar."), "SL-SQ03-002":("P6","unconstrained",""),
 "SL-SQ03-003":("P4","unconstrained",""), "SL-SQ03-004":("P4","unconstrained",""),
 "SL-SQ03-005":("P7","fixed-date","Anniversary of landfall on 28 November; recovery work continuing."),
 "SL-SQ05-001":("P4","fixed-date","Walk runs roughly May to July, arriving at Kataragama for the festival."),
 "SL-SQ06-001":("P5","fixed-date","Twenty-five days in August or September."),
 "SL-SQ06-002":("P1","fixed-date","Auction every Tuesday and Wednesday."),
 "SL-SQ06-003":("P7","unconstrained",""), "SL-SQ06-004":("P4","seasonal","Yala closes annually for the dry season."),
 "SL-SQ02-006":("P4","seasonal",""), "SL-SQ13-001":("P6","seasonal","Conflict peaks around harvest."),
 "SL-SQ04-001":("P7","unconstrained",""), "SL-SQ04-002":("P7","unconstrained",""),
 "SL-SQ13-002":("P5","fixed-date","Feast of the Assumption, 15 August."),
 "SL-SQ07-001":("P5","unconstrained",""), "SL-SQ07-004":("P3","seasonal","Tapping stops in heavy rain."),
 "SL-SQ08-002":("P2","seasonal","Harvest follows the dry months."), "SL-SQ09-002":("P7","unconstrained",""),
 "SL-SQ07-002":("P1","unconstrained",""), "SL-SQ07-003":("P7","unconstrained",""),
 "SL-SQ08-004":("P7","unconstrained",""), "SL-SQ08-007":("P7","unconstrained",""),
 "SL-SQ10-004":("P7","unknown","Place not established."), "SL-SQ08-005":("P3","seasonal","Risk and warnings peak in the monsoon."),
 "SL-SQ10-002":("P2","unconstrained",""), "SL-SQ10-003":("P1","unconstrained",""),
 "SL-SQ10-007":("P5","fixed-date","Temple festival calendar."), "SL-SQ09-003":("P3","fixed-date","An initiation happens on a set date."),
 "SL-SQ10-005":("P7","fixed-date","The examination is held annually."), "SL-SQ10-008":("P7","unconstrained",""),
 "SL-SQ10-006":("P7","fixed-date","School season and the March big match."),
 "SL-SQ09-001":("P2","seasonal","Peeling follows the harvest cycle."),
 "SL-SQ02-005":("P2","seasonal","The reef is only approachable in a short calm season."),
 "SL-SQ21-006":("P5","unconstrained",""), "SL-SQ10-001":("P3","unconstrained",""),
 "SL-SQ12-003":("P7","fixed-date","Vesak, in May."), "SL-SQ11-001":("P3","fixed-date","Season from the December to the May full moon."),
 "SL-SQ12-002":("P7","unconstrained",""), "SL-SQ11-002":("P6","fixed-date","Duruthu new-rice offering in January; observance before the April new year."),
 "SL-SQ11-003":("P7","unknown","Place not established."), "SL-SQ12-001":("P2","seasonal",""),
 "SL-SQ14-001":("P2","fixed-date","Nesting season."), "SL-SQ15-002":("P3","unconstrained",""),
 "SL-SQ15-004":("P3","unconstrained",""), "SL-SQ14-002":("P2","fixed-date","Whale season off the south coast."),
 "SL-SQ15-003":("P7","fixed-date","Start of an academic year."), "SL-SQ23-004":("P4","fixed-date","Clearing and burning before the north-east monsoon."),
 "SL-SQ15-001":("P6","unconstrained",""), "SL-SQ23-001":("P1","unconstrained",""),
 "SL-SQ24-004":("P3","unconstrained",""), "SL-SQ23-007":("P7","unconstrained",""),
 "SL-SQ23-002":("P3","unconstrained",""), "SL-SQ23-008":("P6","fixed-date","The season's allocation meeting."),
 "SL-SQ23-003":("P5","unconstrained",""), "SL-SQ24-005":("P7","fixed-date","Cultivation season."),
 "SL-SQ17-003":("P6","unconstrained",""), "SL-SQ16-001":("P4","fixed-date","Releases happen on a schedule."),
 "SL-SQ24-002":("P3","fixed-date","Ten nights ending on the Esala full moon."),
 "SL-SQ17-001":("P2","unconstrained",""), "SL-SQ17-002":("P1","unconstrained",""),
 "SL-SQ23-009":("P1","unconstrained",""), "SL-SQ22-004":("P1","unconstrained",""),
 "SL-SQ23-006":("P3","unconstrained",""), "SL-SQ16-002":("P7","unconstrained",""),
 "SL-SQ19-003":("P1","unconstrained",""), "SL-SQ17-004":("P7","unconstrained",""),
 "SL-SQ18-003":("P1","unconstrained",""), "SL-SQ18-004":("P7","unconstrained",""),
 "SL-SQ19-002":("P7","unknown","Cannot be planned; depends on a death and an existing relationship."),
 "SL-SQ18-002":("P1","unconstrained",""), "SL-SQ22-008":("P3","seasonal","Reservoir at low water."),
 "SL-SQ22-001":("P4","seasonal","Still nights."), "SL-SQ19-001":("P6","unconstrained",""),
 "SL-SQ18-005":("P1","fixed-date","Easter."), "SL-SQ20-001":("P6","fixed-date","Filling and drawdown of the tanks."),
 "SL-SQ18-001":("P2","fixed-date","26 December, every year."),
 "SL-SQ21-002":("P3","unconstrained",""), "SL-SQ21-001":("P2","unconstrained",""),
 "SL-SQ21-008":("P1","unconstrained",""), "SL-SQ21-003":("P6","unconstrained",""),
 "SL-SQ22-007":("P7","unconstrained",""), "SL-SQ21-007":("P1","seasonal","Erosion is worst in the monsoon."),
 "SL-SQ22-003":("P4","unknown","No collection or reader located."),
 "SL-SQ22-010":("P2","unconstrained",""), "SL-SQ21-004":("P3","seasonal","Restoration work follows the damage."),
 "SL-SQ22-005":("P5","unconstrained",""),
}

ANCHORS={
 "SL-SQ02-001": dict(rank=1, kind="object and sound",
   requirement="A drum has to be followed from the block of wood to a performance in another episode. That means filming the making, marking the specific instrument, and returning to it later.",
   observed="The making and the later use are both real events. Whether the same drum can be followed is a production question, not a claim about anyone's life.",
   audience_first="A craft episode about how a two-toned drum is made.",
   ep100_later="The same drum is heard in the Episode 100 reconstruction, which places the making much earlier in the underlying journey than its release position suggests."),
 "SL-SQ05-001": dict(rank=2, kind="journey",
   requirement="A section of the walk has to be travelled with the pilgrims, and the route has to be recognisable again where it crosses other episodes' ground.",
   observed="The pilgrimage is real, annual and crosses the island. Nothing about it is arranged for the series.",
   audience_first="A self-contained documentary about a two-month walk.",
   ep100_later="The route is the spine of the underlying chronology; Episode 100 shows where Chathura joined it and where he left."),
 "SL-SQ11-001": dict(rank=3, kind="revisited place",
   requirement="The trail has to be climbed in season and revisited out of season, which are two different shoots months apart.",
   observed="The season's opening and closing are real and dated.",
   audience_first="An episode about the people who keep a mountain trail supplied through the night.",
   ep100_later="The out-of-season climb is part of the Episode 100 reconstruction, and it is the first time the audience sees the route empty."),
 "SL-SQ10-001": dict(rank=4, kind="object continuity",
   requirement="A woven piece has to be identifiable, and its later appearance has to be honestly accounted for.",
   observed="The weaving is real. The object's later appearance is a production arrangement and must be labelled as one.",
   audience_first="An episode about the last households weaving hana fibre.",
   ep100_later="The piece is among the objects gathered in the room in Episode 100 Part A."),
 "SL-SQ16-001": dict(rank=5, kind="revisited subject",
   requirement="A specific release has to be filmed, and the same animals looked for afterwards through the monitoring programme.",
   observed="Releases and post-release tracking are real and already recorded by the Department of Wildlife Conservation. This is genuine observed continuity.",
   audience_first="An episode about raising orphaned elephants for release.",
   ep100_later="The return to the park in Episode 100 answers a question the first episode deliberately left open, and may answer it badly."),
 "SL-SQ03-005": dict(rank=6, kind="context revealed later",
   requirement="No extra filming. The requirement is editorial: several other episodes were filmed in places this cyclone damaged, and that has to be tracked rather than discovered late.",
   observed="Entirely observed. The cyclone damaged the hill railway, cut off tea estates and prompted inland fisheries restoration in the east, all of which appear in other episodes in this catalogue.",
   audience_first="An episode about recovery from a named disaster.",
   ep100_later="Episode 100 shows how many of the other episodes sit on one side or the other of this date, which is the only hard chronological marker the series actually has."),
 "SL-SQ20-001": dict(rank=7, kind="system continuity",
   requirement="Upstream and downstream points in the same cascade have to be filmed as one system, in the filling season and again at drawdown.",
   observed="The cascade is a real hydrological connection between places. Nothing is invented.",
   audience_first="An episode about restoring an ancient irrigation system.",
   ep100_later="The water connects two other episodes that the audience had no reason to connect."),
 "SL-SQ18-001": dict(rank=8, kind="date and place",
   requirement="The commemoration has to be filmed on 26 December, and the same stretch of line filmed on an ordinary day.",
   observed="The annual stop is real and dated.",
   audience_first="An episode about a commemoration twenty-two years after a disaster.",
   ep100_later="The ordinary-day footage is used in Episode 100, where the audience finally sees the place without the ceremony."),
 "SL-SQ22-005": dict(rank=9, kind="journey and ending",
   requirement="The line has to be travelled to its terminus, and that footage held back for the release-order ending.",
   observed="The line, its destruction and its reconstruction are documented facts.",
   audience_first="The last episode of the public journey: a train to the end of a rebuilt line.",
   ep100_later="Episode 100 reveals that this journey was not the end of anything, and that it happened long before the audience was shown it."),
}

# ---------------- build ----------------
order=[lid for s in SEASONS for lid in s["eps"]]
assert len(order)==98, len(order)
assert len(set(order))==98
stories={}
for i,lid in enumerate(sorted(order)):   # ST ids in stable lead-id order, NOT episode order
    stories[lid]=dict(story_id="ST-%03d"%(i+1))
ep=2
for s in SEASONS:
    for pos,lid in enumerate(s["eps"],1):
        L=leads[lid]; st=stories[lid]
        ph,conf,cal=PHASE[lid]
        st.update(lead_id=lid, title=L["title"], premise=L["situation"][:400],
          candidate_status=L["candidate_status"], episode=ep, season=s["id"], pos_in_season=pos,
          season_size=s["episodes"], territory=L["territory"], sq=L["sq"],
          primary_idea=L["primary_idea"], supporting_ideas=L["supporting_ideas"],
          place=L["place"], district=L["district"], province=L["province"],
          activity=L["activity"], change=L["change"], unresolved=L["unresolved"],
          access=L["access"], ethics=L["ethics"], sources=L["sources"],
          chron_phase=ph, chron_confidence=conf, calendar=cal,
          anchor=("yes" if lid in ANCHORS else "no"), season_piece=s["piece"])
        ep+=1
assert ep==100, ep

out=dict(rejected=REJECTED, seasons=[{k:v for k,v in s.items()} for s in SEASONS],
         phases=PHASES, anchors=ANCHORS, stories=stories,
         segments={
          "SEG-E100A":dict(name="Episode 100 Part A", chron_order=8,
            content="The missing events before Episode 1: the crowded-location sequence, the return to the room, the ten accumulated objects shown together, the packing, the motorcycle departure and the travel toward Hunnasgiriya and Meemure, until the existing Episode 1 footage connects.",
            source="User-supplied canon. Not documented anywhere in this repository."),
          "SEG-E001":dict(name="Episode 1", chron_order=9,
            content="The monastery experience. Ends with Chathura disappearing into the forest.",
            source="User-supplied canon. Not documented anywhere in this repository."),
          "SEG-E100B":dict(name="Episode 100 Part B", chron_order=10,
            content="Continues from the forest ending: the teacher, the meditation and conversation, and the reconstruction of the larger journey.",
            source="User-supplied canon. Not documented anywhere in this repository."),
         })
json.dump(out, open(os.path.join(D,"stories.json"),"w"), indent=1, ensure_ascii=False)
print("stories:",len(stories),"episodes 2..%d"%(ep-1),"anchors:",len(ANCHORS),"rejected:",len(REJECTED))
