# -*- coding: utf-8 -*-
"""Regenerate every readable .md table and every .csv in this folder from the authoritative records.

SAFE REGENERATION. Reads, never writes:
    content/05-story-leads/SL-*.md      lead cards (research fields)
    data/stories.json                   planning (release order, chronology, anchors, premises)
    data/connections.json               connections
    content/03-idea-bank/ideas/*.md     idea cards
Writes only the generated files listed in OUTPUTS below.

    python3 tools/build.py            write the generated files
    python3 tools/build.py --check    exit 1 if any generated file on disk differs from the data (writes nothing)
"""
import collections, csv, io, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import series  # noqa: E402

H = series.H
OUTPUTS = ["EPISODE-MATRIX.csv", "STORY-CONNECTIONS.csv", "IDEA-COVERAGE.csv", "SEASON-ARC-MAP.md",
           "CONTINUITY-ANCHORS.md", "HIDDEN-CHRONOLOGY.md", "EPISODE-001-TO-100-CONNECTION.md", "EPISODE-MATRIX.md",
           "STORY-CANDIDATE-CATALOG.md", "NEEDS-ATTENTION.md"]

HEAD = "<!-- GENERATED by tools/build.py. Edit the records named in README.md, then run tools/rebuild.py. -->\n\n"
SPOILER = ("> **SPOILER-SENSITIVE.** This file contains the hidden structure of the series.\n"
           "> The label is an editorial marker and enforces nothing. **This GitHub repository is public, and this "
           "folder has already been pushed to it** (checked 2026-09-18), so its contents are world-readable and may "
           "be indexed or cached even if later deleted. The explorer app can hide spoilers from its own pages "
           "(`EXPLORER_SPOILERS=hide`), but that does not make files in a public repository private. See CONFLICT-04 in "
           "[SERIES-CANON.md](SERIES-CANON.md).\n")


def ids(xs):
    return ", ".join("`%s`" % x for x in xs) or "none"


def render():
    d = series.load()
    ST, CX, IB, SEAS, ANCH, SEG = d["stories"], d["CX"], d["ideas"], d["seasons"], d["anchors"], d["segments"]
    REJ, CONF, ARCH, CARDS = d["rejected"], d["conflicts"], d["archive"], d["cards"]
    DIFF = d["raw"].get("idea_differentiation", {})
    order = list(ST)                                  # release order
    by_lead = {v["lead_id"]: v for v in ST.values()}
    ACCEPTED = sorted([i for i in IB.values() if i["status"] == "accepted for research"], key=lambda x: x["id"])
    out = {}

    # idea tiers and territories, from the story-discovery layer
    import re
    pm = open(os.path.join(series.CONTENT, "04-story-discovery", "philosophy-map.md"), encoding="utf-8").read()
    app = pm.split("## Appendix A")[1].split("## Appendix B")[0] if "## Appendix A" in pm else ""
    for line in app.split("\n"):
        cells = [c.strip() for c in line.strip().strip("|").split(" | ")]
        idm = re.findall(r"C\d{3}-I\d{2}", cells[0]) if cells else []
        if idm and idm[0] in IB and len(cells) > 2:
            IB[idm[0]]["territory"] = cells[2]
    mx = open(os.path.join(series.CONTENT, "04-story-discovery", "documentary-potential-matrix.md"), encoding="utf-8").read()
    for line in mx.split("\n"):
        if not line.startswith("| C"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split(" | ")]
        if len(cells) >= 15 and cells[0] in IB:
            IB[cells[0]]["tier"] = cells[12].replace("*", "").strip()

    def connected(sid):
        return sorted({x["to_id"] if x["from_id"] == sid else x["from_id"] for x in ST[sid]["connections"]})

    def seg_link(sid, seg):
        for x in ST[sid]["connections"]:
            if seg in (x["from_id"], x["to_id"]):
                return "%s (%s): %s" % (x["type"], x["status"], x["explanation"])
        return "not applicable"

    def season_of(v):
        return next(s for s in SEAS if s["id"] == v["season"])

    def role(sid):
        v = ST[sid]; s = season_of(v); n = len(s["eps"]); p = v["pos_in_season"]
        if p == 1:
            r = "Opens the season. Puts the season's question on the table: %s" % s["question"]
        elif p == n:
            r = "Closes the season. Carries the shift: %s" % s["shift"].split(".")[0] + "."
        else:
            r = "Develops the season's contrast."
        if v["anchor"] == "yes":
            r += " Also a proposed continuity anchor (rank %d)." % ANCH[v["lead_id"]]["rank"]
        return r + " (Proposal.)"

    def mech(sid):
        k = IB.get(ST[sid]["primary_idea"], {})
        return "%s - %s" % (k.get("title", ""), k.get("core", ""))

    def access_status(v):
        L = v["lead"]
        if not L:
            return "not yet established"
        return "contact made: %s; filming access: %s; consent: %s" % (L["contact_made"] or "not recorded",
                                                                      L["filming_access"], L["consent_status"])

    # ---------------- EPISODE-MATRIX.csv ----------------
    cols = ["story_id", "lead_id", "working_title", "premise", "candidate_status", "episode", "season",
            "position_in_season", "territory", "research_question", "primary_idea", "supporting_ideas",
            "philosophical_mechanism", "observable_basis", "role_in_season", "chronology_phase",
            "chronology_confidence", "calendar_constraint", "continuity_role", "connected_ids",
            "episode_1_connection", "episode_100_payoff", "research_status", "research_stage", "sources_opened",
            "sources_total", "claim_review", "subject_identified", "consent_status", "filming_access",
            "access_status", "main_missing_item", "main_unresolved_dependency"]
    buf = io.StringIO()
    w = csv.writer(buf, quoting=csv.QUOTE_ALL, lineterminator="\n")
    w.writerow(cols)
    for sid in order:
        v = ST[sid]; lid = v["lead_id"]; lad = v["ladder"]
        e100 = seg_link(sid, "SEG-E100A")
        if e100 == "not applicable":
            e100 = seg_link(sid, "SEG-E100B")
        w.writerow([sid, lid, v["title"], v["premise"], v["candidate_status"], v["episode"], v["season"],
                    v["pos_in_season"], v["territory"], v["sq"], v["primary_idea"], "; ".join(v["supporting_ideas"]),
                    mech(sid), "Interpretation, not a finding. Reported activity: %s" % v["activity"], role(sid),
                    v["chron_phase"], v["chron_confidence"], v["calendar"] or "none",
                    ("proposed continuity anchor (rank %d, %s)" % (ANCH[lid]["rank"], ANCH[lid]["kind"])) if v["anchor"] == "yes" else "standalone",
                    "; ".join(connected(sid)) or "none", seg_link(sid, "SEG-E001"), e100,
                    v["research_status"], lad["stage_label"], lad["opened"], lad["total"], v["claim_review"],
                    v["subject_identified"], v["consent_status"], v["filming_access"], access_status(v),
                    series.main_missing(v), v["unresolved"]])
    out["EPISODE-MATRIX.csv"] = buf.getvalue()

    # ---------------- STORY-CONNECTIONS.csv ----------------
    buf = io.StringIO()
    w = csv.writer(buf, quoting=csv.QUOTE_ALL, lineterminator="\n")
    w.writerow(["connection_id", "from_id", "to_id", "family", "relationship_type", "explanation",
                "source_or_planning_basis", "evidence_status", "initial_audience_interpretation",
                "later_interpretation", "required_footage_or_research", "spoiler_visibility"])
    for x in CX:
        w.writerow([x["id"], x["from_id"], x["to_id"], series.FAMILY.get(x["type"], "other"), x["type"],
                    x["explanation"], x["basis"], x["status"], x["first_reading"], x["later_reading"], x["required"],
                    x["spoiler"]])
    out["STORY-CONNECTIONS.csv"] = buf.getvalue()

    # ---------------- IDEA-COVERAGE.csv ----------------
    prim = collections.defaultdict(list); supp = collections.defaultdict(list)
    for sid in order:
        prim[ST[sid]["primary_idea"]].append(sid)
        for i in ST[sid]["supporting_ideas"]:
            supp[i].append(sid)
    buf = io.StringIO()
    w = csv.writer(buf, quoting=csv.QUOTE_ALL, lineterminator="\n")
    w.writerow(["idea_id", "idea_title", "tier", "territory", "primary_story_ids", "supporting_story_ids",
                "use", "how_the_uses_differ", "unused_or_deferred", "repetition_or_interpretation_concern"])
    for i in ACCEPTED:
        k = i["id"]; p = prim.get(k, []); s = supp.get(k, [])
        use = "primary and supporting" if p and s else "primary" if p else "supporting only" if s else "not used"
        diff = DIFF.get(k, "")
        if not diff and len(p) == 1:
            diff = "Single use as primary."
        if not diff and not p and s:
            diff = "Used only to widen the reading of stories led by another idea."
        if not diff and not p and not s:
            diff = "not applicable"
        if len(p) > 1 and not DIFF.get(k):
            diff = "NOT YET DIFFERENTIATED: used as primary by %d stories and no differentiation note is recorded in data/stories.json." % len(p)
        conc = ""
        if len(p) > 2:
            conc = "Used as the primary idea of %d episodes. Watch for the series repeating one shape of story." % len(p)
        elif len(p) == 2:
            conc = ("Used twice as primary. The two uses are distinguished in the previous column; if that distinction "
                    "weakens in the edit, one should be re-led by another idea.")
        if k == "C093-I02":
            conc = (conc + " ").strip() + " Marked *Do not advance* in the documentary potential matrix and is correctly unused here."
        if i.get("tier") == "Tier C" and p:
            conc = (conc + " ").strip() + (" Tier C card leading an episode: the matrix rates it as a supporting lens, "
                                           "so the episode must stand on its situation, not on the idea.")
        w.writerow([k, i["title"], i.get("tier", ""), i.get("territory", ""), "; ".join(p) or "none",
                    "; ".join(s) or "none", use, diff, "in use" if (p or s) else "not used; kept visible and available",
                    conc or "none"])
    out["IDEA-COVERAGE.csv"] = buf.getvalue()

    # ================= Markdown =================
    n_ev = sum(1 for s in order if ST[s]["candidate_status"] == "evidenced-situation")
    n_un = sum(1 for s in order if ST[s]["candidate_status"] == "unverified-lead")
    counts = (
        "> **Counts, kept separate.** %d provisional candidates are catalogued (Episodes 2-99). **%d** have their core "
        "situation reported in published sources (`evidenced-situation`) and **%d** are specific possibilities still "
        "awaiting confirmation (`unverified-lead`). Sources opened and checked: **%d of %d** citations. Evidence "
        "reviewed: **%d**. Subjects identified: **%d**. Filming access confirmed: **%d**. Production-ready: **%d**. "
        "A catalogue of provisional candidates is not a set of finished stories.\n"
        % (len(order), n_ev, n_un, sum(ST[s]["ladder"]["opened"] for s in order),
           sum(ST[s]["ladder"]["total"] for s in order),
           sum(1 for s in order if ST[s]["claim_review"] != "not reviewed"),
           sum(1 for s in order if ST[s]["subject_identified"] == "yes"),
           sum(1 for s in order if ST[s]["filming_access"] == "confirmed"),
           sum(1 for s in order if ST[s]["ladder"]["stage"] == len(series.LADDER))))

    # ---- SEASON-ARC-MAP.md ----
    t = [HEAD, "# Season Arc Map\n",
         "Ten seasons, 99 core episodes including Episode 1. Episode 100 is separate and is not counted here.\n",
         "**Everything in this file is a proposal.** Season 1's episode count is not documented anywhere in this "
         "repository (CONFLICT-02), the ten season pieces are not documented either (CONFLICT-03), and no transformation "
         "in Chathura's own life is claimed. The progression is a way of arranging real documentaries so that watching "
         "them in order does something; it is not a ladder and it does not end in enlightenment.\n",
         counts,
         "## Shape\n", "| Season | Title | Declared episodes | Range | Stories placed | Proposed anchors | Season piece slot |",
         "|---|---|---|---|---|---|---|"]
    tot = 0
    for s in SEAS:
        eps = [by_lead[l]["episode"] for l in s["eps"]]; a = sum(1 for l in s["eps"] if l in ANCH); tot += s["episodes"]
        rng = "E%d-E%d" % (min(eps) if s["id"] != "S01" else 1, max(eps))
        t.append("| %s | %s | %d | %s | %d | %d | %s |" % (s["id"], s["title"], s["episodes"], rng, len(s["eps"]), a, s["piece"]))
    t.append("| **Total** | | **%d** | E1-E99 | **%d** | **%d** | 10 slots |" % (tot, sum(len(s["eps"]) for s in SEAS), len(ANCH)))
    t.append("\nSeason 1 contains Episode 1 plus %d stories; every other season is entirely stories.\n" % len(SEAS[0]["eps"]))
    t.append("**Season pieces.** `SP-01` to `SP-10` are empty slots. No object is assigned to any of them, because no "
             "season piece is described anywhere in this repository.\n")
    for s in SEAS:
        eps = [by_lead[l] for l in s["eps"]]
        t.append("\n---\n\n## %s - %s\n" % (s["id"], s["title"]))
        t.append("*Status: %s.*\n" % s.get("status", "proposed"))
        t.append("**Central human question.** %s\n" % s["question"])
        t.append("**Where the season starts.** %s\n" % s["assumption"])
        t.append("**Contrasts inside the season.** %s\n" % s["contrasts"])
        t.append("**The shift its closing stories are meant to make possible.** %s\n" % s["shift"])
        t.append("**How it prepares the next season.** %s\n" % s["prepares"])
        t.append("**What it is meant to change about Episode 1.** %s\n" % s["ep1_effect"])
        t.append("**Declared episode count.** %d%s\n" % (s["episodes"], " (Episode 1 plus %d stories)" % len(s["eps"]) if s["id"] == "S01" else ""))
        t.append("**Proposed continuity contribution.** %s\n" % (", ".join("%s (%s)" % (by_lead[l]["story_id"], ANCH[l]["kind"]) for l in s["eps"] if l in ANCH) or "none; this season carries no anchor, which is deliberate"))
        t.append("**Season piece slot.** %s - no object assigned.\n" % s["piece"])
        t.append("| Ep | Story | Title | Territory | Primary idea | Candidate status | Research stage |")
        t.append("|---|---|---|---|---|---|---|")
        if s["id"] == "S01":
            t.append("| 1 | `SEG-E001` | Episode 1 (user-supplied canon) | not applicable | not applicable | framing | not applicable |")
        for v in eps:
            t.append("| %d | `%s` | %s%s | %s | `%s` | %s | %s |" % (v["episode"], v["story_id"], v["title"],
                     " **(proposed anchor)**" if v["anchor"] == "yes" else "", v["territory"], v["primary_idea"],
                     v["candidate_status"], v["ladder"]["stage_label"]))
    out["SEASON-ARC-MAP.md"] = "\n".join(t) + "\n"

    # ---- CONTINUITY-ANCHORS.md ----
    t = [HEAD, "# Continuity Anchors\n", SPOILER,
         "\n## Status\n",
         "**Every anchor is a proposal.** None of the continuity described here has been filmed, and the underlying "
         "situations are reported in published sources that have mostly been seen only as search results. Each entry "
         "separates what the sources report from what the production would have to arrange.\n",
         "\n## Why nine\n",
         "The requirement is 8 to 10. **Nine is the recommendation.** Ten would invite one anchor per season and collide "
         "with the ten season pieces, which are a separate count. Eight leaves a long stretch with nothing carrying "
         "forward. Nine allows an uneven distribution: Seasons 4 and 7 carry none, so a season is never obliged to "
         "manufacture one.\n",
         "The other %d episodes may carry quiet echoes, but none depends on another episode to make sense.\n" % (len(order) - len(ANCH)),
         "\n| Rank | Story | Episode | Season | Kind | Status |", "|---|---|---|---|---|---|"]
    for l, a in sorted(ANCH.items(), key=lambda kv: kv[1]["rank"]):
        v = by_lead[l]
        t.append("| %d | `%s` %s | E%d | %s | %s | %s |" % (a["rank"], v["story_id"], v["title"], v["episode"], v["season"], a["kind"], a.get("status", "proposed")))
    for l, a in sorted(ANCH.items(), key=lambda kv: kv[1]["rank"]):
        v = by_lead[l]
        t.append("\n---\n\n### %d. `%s` - %s\n" % (a["rank"], v["story_id"], v["title"]))
        t.append("- **Episode / season:** E%d, %s, position %d\n- **Lead:** `%s`\n- **Candidate status:** %s\n- **Research stage:** %s\n- **Continuity kind:** %s\n- **Status:** %s\n"
                 % (v["episode"], v["season"], v["pos_in_season"], l, v["candidate_status"], v["ladder"]["stage_label"], a["kind"], a.get("status", "proposed")))
        t.append("**Proposed place in the underlying journey.** Chronology phase %s, confidence `%s`.%s\n"
                 % (v["chron_phase"], v["chron_confidence"], (" Calendar constraint: %s" % v["calendar"]) if v["calendar"] else ""))
        t.append("**What the audience sees first.** %s\n" % a["audience_first"])
        t.append("**What Episode 100 would later clarify (proposal).** %s\n" % a["ep100_later"])
        t.append("**Practical requirement.** %s\n" % a["requirement"])
        t.append("**Evidence, and what is only planned.** %s\n" % a["evidence"])
        cs = v["connections"]
        t.append("**Connections (%d).**\n" % len(cs))
        for x in cs:
            t.append("- `%s` `%s` to `%s` - *%s* (%s). %s" % (x["id"], x["from_id"], x["to_id"], x["type"], x["status"], x["explanation"]))
    t.append("\n---\n\n## What is not an anchor, on purpose\n")
    t.append("Nothing that depends on a bereaved family, a patient, a person in treatment, a child or a community in a "
             "live dispute with the state has been given a structural job in the series. If such an episode cannot be "
             "made, the series loses an episode, not a spine.\n")
    out["CONTINUITY-ANCHORS.md"] = "\n".join(t) + "\n"

    # ---- HIDDEN-CHRONOLOGY.md ----
    byph = collections.defaultdict(list)
    for sid in order:
        byph[ST[sid]["chron_phase"]].append(sid)
    fixed = [s for s in order if ST[s]["chron_confidence"] == "fixed-date"]
    t = [HEAD, "# Hidden Chronology\n", SPOILER,
         "\n## What this is, and what it is not\n",
         "This is a **provisional production plan**, not a record of when anything happened. Nothing here dates a real "
         "documentary event and no subject's life is placed on a timeline. Only one relationship is fixed: the order of "
         "the three framing segments, which the project owner supplied. Every phase and every story's place in a phase "
         "is a proposal.\n",
         "**The ordering is partial.** Phases are ordered relative to one another. Stories inside a phase are **not** "
         "ordered, and no claim is made that they were filmed consecutively or in the same year.\n",
         "\n## Confirmed, reported and proposed\n",
         "| Kind | What | Status |", "|---|---|---|",
         "| Fixed by the owner | `SEG-E100A` -> `SEG-E001` -> `SEG-E100B` | user-supplied canon |"]
    for x in CX:
        if series.FAMILY.get(x["type"]) == "chronological" and x["status"] != "proposal":
            t.append("| Reported in sources | `%s` %s -> %s: %s | %s |" % (x["id"], x["from_id"], x["to_id"], x["explanation"], x["status"]))
    t.append("| Proposed | The phase order P1 -> P6 and every story's phase | proposal |")
    t.append("| Not assigned | %d stories in P7 | no position claimed |" % len(byph.get("P7", [])))
    t.append("\n## Calendar conflicts (unresolved)\n")
    t.append("%d of the %d stories are labelled `fixed-date`. Several of those dates cannot all be met in one pass "
             "through the island. The conflicts below are recorded, not resolved; resolving them means deciding how many "
             "years or journeys the hidden chronology covers, and **no date is invented here to make them fit**.\n"
             % (len(fixed), len(order)))
    for c in CONF:
        t.append("### %s - %s\n\n*Status: %s.* Stories: %s.\n\n%s\n\n**Needed:** %s\n" % (c["id"], c["title"], c["status"], ids(c["stories"]), c["detail"], c["needs"]))
    t += ["\n## Order\n", "| # | Phase | What it covers | Status | Stories |", "|---|---|---|---|---|"]
    for n, p in enumerate(d["phases"], 1):
        t.append("| %d | `%s` %s | %s | %s | %d |" % (n, p["id"], p["name"], p["description"], p["status"], len(byph.get(p["id"], []))))
    for k, seg in sorted(SEG.items(), key=lambda kv: kv[1]["chron_order"]):
        t.append("| %d | `%s` | %s | %s | 1 segment |" % (seg["chron_order"], k, seg["name"], seg.get("status", "")))
    t.append("\n```\n... the 98 stories, partially ordered (proposal) ...\n        |\n   SEG-E100A   Episode 100 Part A\n"
             "        |\n   SEG-E001    Episode 1\n        |\n   SEG-E100B   Episode 100 Part B\n```\n")
    for p in d["phases"]:
        ss = byph.get(p["id"], [])
        t.append("\n---\n\n## `%s` %s\n\n%s\n\n**%d stories. Unordered within the phase. Status: %s.**\n" % (p["id"], p["name"], p["description"], len(ss), p["status"]))
        t.append("| Story | Ep | Title | Place | Confidence | Calendar constraint |")
        t.append("|---|---|---|---|---|---|")
        for sid in ss:
            v = ST[sid]
            t.append("| `%s` | %d | %s | %s | `%s` | %s |" % (sid, v["episode"], v["title"], v["place"], v["chron_confidence"], v["calendar"] or "none"))
    t.append("\n---\n\n## Confidence values\n")
    t.append("| Value | Meaning |\n|---|---|\n"
             "| `fixed-date` | Tied to a recurring date or season named in the lead. Several name the occasion but not the day. |\n"
             "| `seasonal` | Constrained by weather, access or a work cycle, but not to a specific date. |\n"
             "| `unconstrained` | Could be filmed at any time of year. |\n"
             "| `unknown` | The place or the timing has not been established. |\n")
    cnt = collections.Counter(ST[s]["chron_confidence"] for s in order)
    t.append("\nAcross the %d: " % len(order) + ", ".join("`%s` %d" % (k, v) for k, v in sorted(cnt.items())) + ".\n")
    t.append("\n## Rules for using this file\n"
             "- A story's phase may change without its story ID changing.\n"
             "- A phase is not a shoot. Do not schedule from this file.\n"
             "- If real footage contradicts a phase, the phase is wrong. **Do not re-date the footage.**\n")
    out["HIDDEN-CHRONOLOGY.md"] = "\n".join(t) + "\n"

    # ---- EPISODE-001-TO-100-CONNECTION.md ----
    t = [HEAD, "# Episode 1 and Episode 100\n", SPOILER, "\n## The sequence\n",
         "Preserved exactly as the project owner supplied it. **None of it is documented anywhere else in this "
         "repository**; it is recorded as user-supplied canon.\n",
         "```\nSEG-E100A  ->  SEG-E001  ->  SEG-E100B\n```\n", "| Segment | Content, as supplied | Status |", "|---|---|---|"]
    for k in ["SEG-E100A", "SEG-E001", "SEG-E100B"]:
        t.append("| `%s` %s | %s | %s |" % (k, SEG[k]["name"], SEG[k]["content"], SEG[k].get("status", "")))
    t.append("\n**Episode 1 is the destination of the core chronological journey** and is released first. **Part B is "
             "its continuation and completion.** Episode 100 is a completion and reconstruction episode and is **not** "
             "one of the 98 documentary candidates.\n")
    segs = [x for x in CX if x["from_id"].startswith("SEG-") or x["to_id"].startswith("SEG-")]
    t.append("\n## Everything in the catalogue that touches the framing segments\n")
    t.append("\n%d connections of %d involve a framing segment. **All of them are proposals**: none of the footage they "
             "describe exists. The remaining %d are between stories.\n" % (len(segs), len(CX), len(CX) - len(segs)))
    t.append("\n| ID | From | To | Type | Evidence status | What the audience reads first | What it would become |")
    t.append("|---|---|---|---|---|---|---|")
    for x in segs:
        t.append("| `%s` | `%s` | `%s` | %s | %s | %s | %s |" % (x["id"], x["from_id"], x["to_id"], x["type"], x["status"], x["first_reading"], x["later_reading"]))
    t.append("\n## What Episode 100 has to do, and what it must not do\n")
    t.append("**Part A must supply**, in the order the owner gave: the crowded-location sequence; the return to the room; "
             "the ten accumulated objects shown together; the packing; the motorcycle departure; and the travel toward "
             "Hunnasgiriya and Meemure, until it meets the existing Episode 1 footage.\n")
    t.append("\n**Two of the ten objects are proposed** from continuity anchors: the drum from `%s` and the woven piece "
             "from `%s`. Neither has been acquired or filmed. The other eight are **not assigned**, and none should be "
             "invented.\n" % (by_lead["SL-SQ02-001"]["story_id"], by_lead["SL-SQ10-001"]["story_id"]))
    t.append("\n**Part B must continue** from the forest ending with the teacher and the meditation or conversation, and "
             "reconstruct the larger journey. It does not need, and should not attempt, a callback to all 98.\n")
    t.append("\n**It must not**: re-date any real documentary event to fit the sequence; imply that any participant was "
             "part of Chathura's journey in a way they were not; present an arranged object placement as an observed "
             "coincidence; or turn the 98 into a puzzle.\n")
    t.append("\n## The one thing that could break this\n")
    t.append("Episode 1 exists already. If its footage contradicts the Part A material, Part A has to bend, not Episode 1. "
             "Nothing in this repository describes the Episode 1 footage, so **this cannot be checked here**.\n")
    out["EPISODE-001-TO-100-CONNECTION.md"] = "\n".join(t) + "\n"

    # ---- EPISODE-MATRIX.md ----
    t = [HEAD, "# Episode Matrix\n",
         "%d primary candidate rows, one for each of Episodes 2 to 99. Episode 1 and Episode 100 are framing segments, "
         "not candidate rows.\n" % len(order),
         "The same rows are in [EPISODE-MATRIX.csv](EPISODE-MATRIX.csv). Both are generated from the records by "
         "`tools/build.py`; `tools/validate.py` fails if either differs from the records.\n", counts,
         "\n## A. Identity and placement (proposal)\n",
         "| Ep | Season | Pos | Story | Lead | Working title | Candidate status | Research stage |", "|---|---|---|---|---|---|---|---|"]
    for sid in order:
        v = ST[sid]
        t.append("| %d | %s | %d | `%s` | `%s` | %s%s | %s | %s |" % (v["episode"], v["season"], v["pos_in_season"], sid,
                 v["lead_id"], v["title"], " **(proposed anchor)**" if v["anchor"] == "yes" else "", v["candidate_status"], v["ladder"]["stage_label"]))
    t.append("\n## B. Premise, idea and what the sources report can be seen\n")
    t.append("The mechanism is an interpretation held by the production team and is never told to a participant as an "
             "explanation of their life. The observable column is what published sources report happens there; nothing "
             "has been filmed.\n")
    t.append("| Story | Premise | Terr. | SQ | Primary idea | Supporting | Hidden mechanism (interpretation) |")
    t.append("|---|---|---|---|---|---|---|")
    for sid in order:
        v = ST[sid]
        t.append("| `%s` | %s | %s | %s | `%s` | %s | %s |" % (sid, v["premise"], v["territory"], v["sq"], v["primary_idea"], ids(v["supporting_ideas"]), mech(sid)))
    t.append("\n## C. Structure: season role, chronology and continuity (all proposals)\n")
    t.append("| Story | Role in the season | Chron. phase | Confidence | Continuity role | Connected | Ep 1 | Ep 100 |")
    t.append("|---|---|---|---|---|---|---|---|")
    for sid in order:
        v = ST[sid]; lid = v["lead_id"]
        e1 = seg_link(sid, "SEG-E001"); e100 = seg_link(sid, "SEG-E100A")
        if e100 == "not applicable":
            e100 = seg_link(sid, "SEG-E100B")
        t.append("| `%s` | %s | %s | `%s` | %s | %s | %s | %s |" % (sid, role(sid), v["chron_phase"], v["chron_confidence"],
                 ("anchor %d" % ANCH[lid]["rank"]) if v["anchor"] == "yes" else "standalone", ids(connected(sid)),
                 "yes" if e1 != "not applicable" else "not applicable", "yes" if e100 != "not applicable" else "not applicable"))
    t.append("\n## D. Evidence and production reality\n")
    t.append("| Story | Place | District | Sources opened | Claim review | Subject | Access | Main missing item | Main unresolved dependency |")
    t.append("|---|---|---|---|---|---|---|---|---|")
    for sid in order:
        v = ST[sid]; lad = v["ladder"]
        t.append("| `%s` | %s | %s | %d of %d | %s | %s | %s | %s | %s |" % (sid, v["place"], v["district"], lad["opened"], lad["total"],
                 v["claim_review"], "identified" if v["subject_identified"] == "yes" else "not identified", v["filming_access"],
                 series.main_missing(v), v["unresolved"]))
    t.append("\n## Rejected at selection, and why\n")
    t.append("%d leads that reached candidate development were **not** placed in an episode. Their cards are kept.\n" % len(REJ))
    t.append("\n| Lead | Title | Reason |\n|---|---|---|")
    for lid, why in sorted(REJ.items()):
        t.append("| `%s` | %s | %s |" % (lid, CARDS[lid]["title"] if lid in CARDS else ARCH[lid]["title"], why))
    hold = [c for c in CARDS.values() if c["research_status"] == "on hold"]
    t.append("\n## Held, and why\n")
    t.append("%d leads are held out of the portfolio. Two of the three concern Tamil communities in the north in "
             "disputes with the state; that pattern is a bias in the portfolio, recorded so that the owner decides "
             "about it rather than inheriting it.\n" % len(hold))
    t.append("\n| Lead | Title | Reason for the hold |\n|---|---|---|")
    for c in hold:
        t.append("| `%s` | %s | %s |" % (c["lead_id"], c["title"], " ".join(c["hold_reason"].replace("**On hold.**", "").split())))
    out["EPISODE-MATRIX.md"] = "\n".join(t) + "\n"

    # ---- STORY-CANDIDATE-CATALOG.md ----
    def difficulty(v):
        txt = (v["access"] + " " + v["ethics"] + " " + v["place"]).lower(); pts = 0; why = []
        for k, wgt, lab in [("ministry", 2, "ministry or national approval"), ("department of wildlife", 2, "wildlife department permit"),
                            ("permission", 1, "a named permission holder"), ("gatekeep", 1, "a gatekeeper who is also a party"),
                            ("safeguarding", 2, "a safeguarding protocol"), ("children", 2, "subjects who cannot consent for themselves"),
                            ("child", 1, "children present"), ("consent", 1, "consent that is hard to obtain"), ("season", 1, "a seasonal window"),
                            ("dangerous", 2, "physical danger"), ("night", 1, "night filming"), ("remote", 1, "remoteness"),
                            ("company", 1, "a corporate gatekeeper"), ("clinic", 2, "clinical access"), ("hospital", 2, "hospital access"),
                            ("court", 1, "legal restriction"), ("military", 3, "military-controlled ground"), ("illegal", 2, "activity that is unlawful")]:
            if k in txt:
                pts += wgt; why.append(lab)
        if v["chron_confidence"] == "fixed-date":
            pts += 1; why.append("a fixed date that cannot be moved")
        lab = "low" if pts <= 2 else ("moderate" if pts <= 5 else ("high" if pts <= 8 else "very high"))
        return lab, (", ".join(sorted(set(why))) or "nothing beyond ordinary location filming")

    t = [HEAD, "# Story Candidate Catalog\n",
         "The %d documentary candidates, in proposed release order. Each entry is a candidate, not a commission.\n" % len(order),
         counts,
         "> **Three kinds of statement are kept apart in every entry.** *Reported* means a published source says it; "
         "almost every source has been seen only as a search result. *Interpretation* is the production team's reading. "
         "*Proposal* is a production choice that has not happened. Nothing here has been verified on the ground.\n"]
    sim = collections.defaultdict(list)
    for sid in order:
        for oth in order:
            if oth != sid and ST[oth]["primary_idea"] == ST[sid]["primary_idea"]:
                sim[sid].append(oth)
    for x in CX:
        if series.FAMILY.get(x["type"]) == "philosophical" and x["from_id"] in ST and x["to_id"] in ST:
            sim[x["from_id"]].append(x["to_id"]); sim[x["to_id"]].append(x["from_id"])
    for sid in order:
        v = ST[sid]; lid = v["lead_id"]; L = v["lead"]; a = ARCH.get(lid, {}); idea = IB.get(v["primary_idea"], {})
        dl, dw = difficulty(v)
        claims = {c["source"]: c["claim"] for c in (L["claims"] if L else [])}
        t.append("\n---\n\n## E%d - `%s` %s\n" % (v["episode"], sid, v["title"]))
        t.append("| | |\n|---|---|")
        t.append("| **Lead** | `%s` |" % lid)
        t.append("| **Release (proposal)** | Episode %d, %s, position %d of %d |" % (v["episode"], v["season"], v["pos_in_season"], v["season_len"]))
        t.append("| **Candidate status** | `%s` |" % v["candidate_status"])
        t.append("| **Research stage** | %s (sources opened: %d of %d; claim review: %s) |" % (v["ladder"]["stage_label"], v["ladder"]["opened"], v["ladder"]["total"], v["claim_review"]))
        t.append("| **Territory / question** | %s / %s |" % (v["territory"], v["sq"]))
        t.append("| **Primary idea** | `%s` - %s |" % (v["primary_idea"], idea.get("title", "")))
        t.append("| **Supporting ideas** | %s |" % (", ".join("`%s` %s" % (i, IB.get(i, {}).get("title", "")) for i in v["supporting_ideas"]) or "none"))
        t.append("| **Concept sources** | `%s`%s |" % (idea.get("primary_concept", ""),
                 (" supporting " + ", ".join("`%s`" % c for c in idea.get("supporting_concepts", []))) if idea.get("supporting_concepts") else ""))
        t.append("| **Continuity role (proposal)** | %s |" % (("anchor, rank %d (%s)" % (ANCH[lid]["rank"], ANCH[lid]["kind"])) if v["anchor"] == "yes" else "standalone"))
        t.append("| **Chronology (proposal)** | phase `%s`, confidence `%s`%s |" % (v["chron_phase"], v["chron_confidence"], (", calendar: " + v["calendar"]) if v["calendar"] else ""))
        t.append("| **Production difficulty (estimate)** | **%s** - %s |" % (dl, dw))
        t.append("\n**Premise.** %s\n" % v["premise"])
        t.append("**Subject and location (reported).** %s. %s (%s, %s province).\n" % (v["subject"] or "Not yet established", v["place"] or "Not yet established", v["district"], v["province"]))
        t.append("**What is happening (reported, not verified).** %s\n" % (v["situation"] or "Not yet established"))
        t.append("**Observable activity (reported; nothing filmed).** %s\n" % (v["activity"] or "Not yet established"))
        t.append("**Central human question (interpretation, from %s).** %s\n" % (v["sq"], idea.get("question") or "not recorded on the idea card"))
        t.append("**Stakes and uncertainty.** %s The episode does not know how this resolves and must not be cut as though it did.\n" % v["change"])
        t.append("**Evidence (review status per source).**\n")
        for s_ in v["sources"]:
            t.append("- **%s** (%s, accessed %s; %s): %s  \n  <%s>" % (s_["ref"], s_["type"], s_["accessed"],
                     "opened and checked" if s_["review"] == "opened" else "search result only; not opened",
                     claims.get(s_["ref"], s_["notes"]), s_["url"]))
        t.append("\n**Unresolved claims and gaps.** %s\n" % (v["unresolved"] or "Not yet established"))
        t.append("**Research and access route.** %s\n" % (v["access"] or "Not yet established"))
        t.append("**Consent and access status.** %s. Subject identified: %s. Consent: %s. Filming access: %s.\n"
                 % (("Contact made: " + L["contact_made"]) if L else "No lead card", v["subject_identified"], v["consent_status"], v["filming_access"]))
        t.append("**Ethical concerns.** %s\n" % (v["ethics"] or "Not yet established"))
        t.append("**How the philosophical reading works (interpretation).** %s The reading is applied to the situation, not "
                 "to any person's character or motive.\n" % mech(sid))
        t.append("**Evidence that could challenge that reading** (from the idea card's own limits). %s\n" % (idea.get("limits") or "The card records no limits."))
        others = sorted(set(sim[sid]))
        if others:
            t.append("**Similar candidates, and how they differ.**\n")
            for o in others:
                dd = DIFF.get(ST[o]["primary_idea"], "") if ST[o]["primary_idea"] == v["primary_idea"] else ""
                rel = next((x for x in CX if {x["from_id"], x["to_id"]} == {sid, o}), None)
                t.append("- `%s` %s - %s" % (o, ST[o]["title"], dd or (rel["explanation"] if rel else "shares an idea or a question; the subjects, places and stakes differ")))
        else:
            t.append("**Similar candidates.** None in the catalogue shares this candidate's primary idea or question.")
        for key, label in [("merge_note", "Merge note (desk-research archive)"), ("relation_note", "Kept separate from a neighbouring lead"),
                           ("note", "Note"), ("correction", "Correction")]:
            if a.get(key):
                t.append("\n**%s.** %s" % (label, a[key]))
    out["STORY-CANDIDATE-CATALOG.md"] = "\n".join(t) + "\n"

    # ---- NEEDS-ATTENTION.md ----
    names = dict(series.ISSUE_TYPES)
    per = {sid: series.issues_for(ST[sid], d) for sid in order}
    t = [HEAD, "# Needs Attention\n",
         "Actionable gaps, generated from the records by `tools/build.py`. Nothing here is a percentage or a score: each "
         "line is a specific missing item on a specific record. The explorer app shows the same list at `/attention`.\n",
         counts, "\n## Series decisions still open\n",
         "- **CONFLICT-02** Season 1's episode count is not documented; 8 is a proposal.",
         "- **CONFLICT-03** The ten season pieces are not documented; `SP-01` to `SP-10` have no object.",
         "- **CONFLICT-04** The repository is public and the spoiler-sensitive files have been pushed; the owner decides what to do about it.",
         "- **Episode 1 footage** has not been checked against the Episode 100 Part A material."]
    for c in CONF:
        t.append("- **%s** %s (%s). %s" % (c["id"], c["title"], c["status"], c["needs"]))
    t.append("\n## By type\n")
    t.append("| Issue | Stories affected |\n|---|---|")
    for code, label in series.ISSUE_TYPES:
        n = sum(1 for sid in order if any(i["code"] == code for i in per[sid]))
        t.append("| %s | %d |" % (label, n))
    t.append("\n## By story\n")
    for sid in order:
        v = ST[sid]
        t.append("\n### E%d `%s` %s\n" % (v["episode"], sid, v["title"]))
        for i in per[sid]:
            t.append("- **%s.** %s" % (names[i["code"]], i["detail"]))
    out["NEEDS-ATTENTION.md"] = "\n".join(t) + "\n"
    return out


def main():
    out = render()
    check = "--check" in sys.argv
    stale = []
    for name in OUTPUTS:
        p = os.path.join(H, name)
        text = out[name]
        cur = open(p, encoding="utf-8", newline="").read().replace("\r\n", "\n") if os.path.exists(p) else None
        if cur != text:
            stale.append(name)
            if not check:
                open(p, "w", encoding="utf-8", newline="").write(text)
    if check:
        if stale:
            print("Generated files out of date: " + ", ".join(stale))
            sys.exit(1)
        print("All %d generated files match the records." % len(OUTPUTS))
    else:
        print("build: %d files checked, %d rewritten%s" % (len(OUTPUTS), len(stale), (": " + ", ".join(stale)) if stale else ""))


if __name__ == "__main__":
    main()
