# -*- coding: utf-8 -*-
"""Regenerate the machine-derived part of PROGRESS.md from data/leads.json.
Narrative notes per batch live in data/batch-notes.json and are written by hand."""
import json, os, collections, sys
H=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
D=os.path.join(H,"data")
leads=json.load(open(os.path.join(D,"leads.json")))
notes=json.load(open(os.path.join(D,"batch-notes.json"))) if os.path.exists(os.path.join(D,"batch-notes.json")) else {}
STAT=["direction","unverified-lead","evidenced-situation","evidenced-subject","production-ready"]
out=[]
w=out.append
w("<!-- GENERATED BY tools/progress.py FROM data/. Edit data/, not this block. -->")
w("")
w("## Research totals")
w("")
w("| Measure | Count |")
w("|---|---|")
w(f"| Leads opened | **{len(leads)}** |")
w(f"| Leads advancing to candidate development | {sum(1 for l in leads if l['decision']=='advance')} |")
w(f"| Leads held | {sum(1 for l in leads if l['decision']=='hold')} |")
w(f"| Leads rejected | {sum(1 for l in leads if l['decision']=='rejected')} |")
w(f"| Duplicates merged | {sum(1 for l in leads if l['decision']=='duplicate')} |")
w(f"| Distinct sources cited | {len({s['url'] for l in leads for s in l['sources']})} |")
w(f"| Sources confirmed by fetching the page | {sum(1 for l in leads for s in l['sources'] if s['confirmed']=='fetched')} |")
w("")
w("**Candidate status.** No lead is production-ready. None can be: online research cannot establish participant willingness, filming access or production feasibility, and nobody has been contacted.")
w("")
w("This table covers **all leads opened**, not the 98 selected for episodes. Of the 98 placed in the portfolio, 91 are\n`evidenced-situation` and 7 are `unverified-lead`; the rest of the leads below were rejected or held. See\n`VALIDATION-REPORT.md` for the portfolio breakdown.")
w("")
w("| Candidate status | Count (all leads) |")
w("|---|---|")
c=collections.Counter(l["candidate_status"] for l in leads)
for s in STAT: w(f"| `{s}` | {c.get(s,0)} |")
w("")
w("## Coverage")
w("")
w("### By batch")
w("")
w("| Batch | Theme | Leads | Evidenced situations | Territories touched |")
w("|---|---|---|---|---|")
for b in sorted({l["batch"] for l in leads}):
    bl=[l for l in leads if l["batch"]==b]
    ev=sum(1 for l in bl if l["candidate_status"].startswith("evidenced"))
    ts=",".join(sorted({l["territory"] for l in bl}))
    w(f"| {b} | {notes.get(b,{}).get('theme','')} | {len(bl)} | {ev} | {ts} |")
w("")
w("### By province (place of the lead, not of the idea)")
w("")
prov=collections.Counter()
for l in leads:
    for p in str(l.get("province","")).replace(" and ",", ").split(","):
        p=p.strip()
        if p and p!="not established": prov[p]+=1
w("| Province | Leads |")
w("|---|---|")
for p,n in prov.most_common(): w(f"| {p} | {n} |")
w(f"| *place not yet established* | {sum(1 for l in leads if str(l.get('province',''))=='not established')} |")
w("")
w("### By human territory")
w("")
w("| Territory | Leads as primary |")
w("|---|---|")
t=collections.Counter(l["territory"] for l in leads)
for i in range(1,15):
    k=f"T{i:02d}"; w(f"| {k} | {t.get(k,0)} |")
w("")
w("### Research questions used")
w("")
sq=collections.Counter(l["sq"] for l in leads)
used=sorted(sq); unused=[f"SQ{i:02d}" for i in range(1,25) if f"SQ{i:02d}" not in sq]
w("| Question | Leads |")
w("|---|---|")
for k in used: w(f"| {k} | {sq[k]} |")
w("")
w(f"**Questions not yet used:** {', '.join(unused) if unused else 'none'}.")
w("")
w("### Accepted ideas used")
w("")
ideas=collections.Counter()
for l in leads:
    ideas[l["primary_idea"]]+=1
prim=set(ideas); sup=set()
for l in leads: sup.update(l["supporting_ideas"])
w(f"- Distinct ideas used as **primary**: **{len(prim)}** of 148 accepted.")
w(f"- Distinct ideas used as primary **or** supporting: **{len(prim|sup)}** of 148 accepted.")
rep=[f"`{k}` ({n})" for k,n in ideas.most_common() if n>1]
w(f"- Ideas used as primary more than once: {', '.join(rep) if rep else 'none'}. Each repeated use must be differentiated in `IDEA-COVERAGE.csv`.")
w("")
w("## Lead IDs created")
w("")
w("```")
ids=sorted(l["lead_id"] for l in leads)
for i in range(0,len(ids),6): w("  ".join(ids[i:i+6]))
w("```")
w("")
w("## Remaining episode slots")
w("")
w("98 of 98 (Episodes 2-99). Story IDs are assigned only at the selection stage, so no `ST-` ID exists yet.")
w("")
w("<!-- END GENERATED -->")
text="\n".join(out)
p=os.path.join(H,"PROGRESS.md")
cur=open(p,encoding="utf-8").read()
MARK="<!-- GENERATED BY tools/progress.py"
if MARK in cur:
    head=cur.split(MARK)[0]
    tail=cur.split("<!-- END GENERATED -->",1)[1]
    cur=head+text.split("<!-- GENERATED BY tools/progress.py")[0]+text[text.index(MARK):]+tail
    open(p,"w",encoding="utf-8").write(head+text+tail)
else:
    open(p,"w",encoding="utf-8").write(cur.rstrip()+"\n\n---\n\n"+text+"\n")
print("PROGRESS.md updated;", len(leads), "leads")
