# -*- coding: utf-8 -*-
"""Regenerate the generated block of PROGRESS.md from the authoritative records.

Current state comes from the lead cards and data/stories.json. Batch history comes from the frozen desk-research
archive (data/leads.json) and data/batch-notes.json. Only the block between the GENERATED markers is rewritten.
"""
import collections, json, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import series  # noqa: E402

H, D = series.H, series.D
d = series.load()
cards, ST, arch = d["cards"], d["stories"], d["archive"]
notes = json.load(open(os.path.join(D, "batch-notes.json"), encoding="utf-8"))
placed = set(d["sid_of"])
rejected = set(d["rejected"])
held = {k for k, c in cards.items() if c["research_status"] == "on hold"}
merged = [k for k, a in arch.items() if a.get("merged_from")]
cites = [s for c in cards.values() for s in c["sources"]]

out = []
w = out.append
w("<!-- GENERATED BY tools/progress.py. Edit the records, not this block. -->")
w("")
w("## Current totals")
w("")
w("| Measure | Count |")
w("|---|---|")
w("| Lead cards on disk | **%d** |" % len(cards))
w("| Placed in Episodes 2-99 as candidates | %d |" % len(placed))
w("| Rejected at the selection stage (reasons in `EPISODE-MATRIX.md`) | %d |" % len(rejected))
w("| On hold | %d |" % len(held))
w("| Leads that absorbed a merged lead during research | %d |" % len(merged))
w("| Source citations on lead cards | %d |" % len(cites))
w("| Distinct source URLs | %d |" % len({s["url"] for s in cites}))
w("| Citations opened and checked | %d |" % sum(1 for s in cites if s["review"] == "opened"))
w("")
w("Placed, rejected and held add up to %d of the %d cards." % (len(placed) + len(rejected) + len(held), len(cards)))
w("")
w("| Lead `research_status` | Count (all cards) |")
w("|---|---|")
rs = collections.Counter(c["research_status"] for c in cards.values())
for s in ["unverified", "in research", "verified", "on hold", "rejected"]:
    w("| `%s` | %d |" % (s, rs.get(s, 0)))
w("")
w("| Candidate status (the 98 placed) | Count |")
w("|---|---|")
cs = collections.Counter(v["candidate_status"] for v in ST.values())
for s in ["direction", "unverified-lead", "evidenced-situation", "evidenced-subject", "production-ready"]:
    w("| `%s` | %d |" % (s, cs.get(s, 0)))
w("")
w("**No candidate is production-ready.** Nobody has been contacted, so no subject is identified, no consent exists and "
  "there is no filming access anywhere.")
w("")
w("## Coverage (all %d leads)" % len(cards))
w("")
w("### By research batch (desk-research archive)")
w("")
w("| Batch | Theme | Leads | Evidenced situations | Territories touched |")
w("|---|---|---|---|---|")
for b in sorted({a["batch"] for a in arch.values()}):
    bl = [a for a in arch.values() if a["batch"] == b]
    w("| %s | %s | %d | %d | %s |" % (b, notes.get(b, {}).get("theme", ""), len(bl),
      sum(1 for a in bl if a["candidate_status"].startswith("evidenced")), ",".join(sorted({a["territory"] for a in bl}))))
w("")
w("### By human territory (primary, from the lead cards)")
w("")
w("| Territory | Leads | Placed stories |")
w("|---|---|---|")
t = collections.Counter(c["territory"] for c in cards.values())
tp = collections.Counter(v["territory"] for v in ST.values())
for i in range(1, 15):
    k = "T%02d" % i
    w("| %s | %d | %d |" % (k, t.get(k, 0), tp.get(k, 0)))
w("")
w("### Research questions used")
w("")
sq = collections.Counter(c["sq"] for c in cards.values())
unused = ["SQ%02d" % i for i in range(1, 25) if "SQ%02d" % i not in sq]
w(", ".join("%s (%d)" % (k, sq[k]) for k in sorted(sq)) + ".")
w("")
w("**Questions not yet used:** %s." % (", ".join(unused) if unused else "none"))
w("")
w("### Accepted ideas used")
w("")
pa = {c["primary_idea"] for c in cards.values()}
ps = {v["primary_idea"] for v in ST.values()}
alls = ps | {i for v in ST.values() for i in v["supporting_ideas"]}
w("- Across all %d leads: **%d** distinct ideas as primary." % (len(cards), len(pa)))
w("- Across the 98 placed candidates: **%d** distinct ideas as primary, **%d** as primary or supporting (of 148 accepted)." % (len(ps), len(alls)))
rep = collections.Counter(v["primary_idea"] for v in ST.values())
w("- Ideas leading more than one placed candidate: %s. Each is differentiated in `IDEA-COVERAGE.csv`."
  % (", ".join("`%s` (%d)" % (k, n) for k, n in rep.most_common() if n > 1) or "none"))
w("")
w("## Episode slots")
w("")
w("%d of 98 slots (Episodes 2-99) hold a candidate, each with a stable story ID (`ST-001` to `ST-098`). "
  "%d of them are `unverified-lead` and are the most likely to empty on first contact. An emptied slot should be left "
  "empty and reported, not filled from the rejected list." % (len(ST), cs.get("unverified-lead", 0)))
w("")
w("<!-- END GENERATED -->")
text = "\n".join(out)

p = os.path.join(H, "PROGRESS.md")
cur = open(p, encoding="utf-8").read().replace("\r\n", "\n")
START = "<!-- GENERATED BY tools/progress.py"
END = "<!-- END GENERATED -->"
if START in cur and END in cur:
    new = cur.split(START)[0] + text + cur.split(END, 1)[1]
else:
    new = cur.rstrip() + "\n\n---\n\n" + text + "\n"
if "--check" in sys.argv:
    sys.exit(0 if new == cur else 1)
if new != cur:
    open(p, "w", encoding="utf-8", newline="").write(new)
print("PROGRESS.md generated block %s." % ("updated" if new != cur else "unchanged"))
